send log traces to application insights
Azure/azure-iiot-common pull request #10
Opened 2019-07-10 09:23 UTC by Auguzt

2019-07-10 10:16 UTC, marcschier requested changes

2019-07-10 10:16 UTC, marcschier commented on src/Microsoft.Azure.IIoT.Core/src/Diagnostics/Extensions/LogEx.cs
> +        private static string ApplicationInsightsInstrumentationKey;
Why not a method local variable?

2019-07-10 10:16 UTC, marcschier commented on src/Microsoft.Azure.IIoT.Core/src/Diagnostics/Extensions/LogEx.cs
> +                .WriteTo.ApplicationInsights(ApplicationInsightsInstrumentationKey, TelemetryConverter.Traces)
Will this work if the key is null?

2019-07-10 14:04 UTC, Auguzt commented on src/Microsoft.Azure.IIoT.Core/src/Diagnostics/Extensions/LogEx.cs
> +                .WriteTo.ApplicationInsights(ApplicationInsightsInstrumentationKey, TelemetryConverter.Traces)
right, thanks!

2019-07-15 08:40 UTC, marcschier approved these changes

2019-07-15 09:27 UTC, merged